# Generated by Django 5.1.3 on 2025-09-19 01:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('profile_slug', models.CharField(blank=True, max_length=25)),
                ('cell', models.CharField(blank=True, max_length=12)),
                ('linked_in', models.URLField(blank=True)),
                ('snapchat', models.CharField(blank=True, max_length=50)),
                ('profile_photo', models.ImageField(blank=True, upload_to='userPhotos/profile/')),
                ('banner_photo', models.ImageField(blank=True, upload_to='userPhotos/banners/')),
                ('instagram', models.CharField(blank=True, max_length=50)),
                ('whatsapp', models.CharField(blank=True, max_length=12)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('profile_slug',), name='unique_profile_slug')],
            },
        ),
    ]
