# Generated by Django 5.1.3 on 2025-09-19 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardManager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=7)),
                ('alias', models.CharField(blank=True, max_length=60)),
                ('show_profile', models.BooleanField(default=False)),
                ('front_design', models.ImageField(blank=True, upload_to='cardDesigns/')),
                ('rear_design', models.ImageField(blank=True, upload_to='cardDesigns/')),
                ('reroute_url', models.URLField(blank=True)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('token',), name='unique_card_token')],
            },
        ),
    ]
