# Generated by Django 5.1.3 on 2025-09-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardManager', '0004_alter_card_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_slug',
            field=models.CharField(max_length=25),
        ),
    ]
