# Generated by Django 5.1.3 on 2025-10-04 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardManager', '0007_owner_remove_profile_user_profile_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='cardManager.owner'),
        ),
    ]
