# Generated by Django 5.1.3 on 2025-10-05 15:11

import cardManager.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardManager', '0009_remove_card_user_card_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('design_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('front_design', models.ImageField(blank=True, upload_to='cardDesigns/')),
                ('rear_design', models.ImageField(blank=True, upload_to='cardDesigns/')),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='front_design',
        ),
        migrations.RemoveField(
            model_name='card',
            name='rear_design',
        ),
        migrations.AlterField(
            model_name='card',
            name='token',
            field=models.CharField(default=cardManager.utils.gen_card_token, max_length=7),
        ),
        migrations.AddField(
            model_name='card',
            name='design',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cardManager.design'),
            preserve_default=False,
        ),
    ]
