# Generated by Django 5.1.3 on 2025-10-05 15:15

import cardManager.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardManager', '0010_design_remove_card_front_design_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='card',
            name='unique_card_token',
        ),
        migrations.AlterField(
            model_name='card',
            name='token',
            field=models.CharField(default=cardManager.utils.gen_card_token, max_length=7, unique=True),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(fields=('owner', 'alias'), name='unique_card_alias'),
        ),
    ]
