# Generated by Django 5.1.3 on 2025-10-05 15:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardManager', '0011_remove_card_unique_card_token_alter_card_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='rear_design',
        ),
        migrations.AlterField(
            model_name='owner',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
