# Generated by Django 5.1.3 on 2025-10-05 23:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardManager', '0012_remove_design_rear_design_alter_owner_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_used', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='cardManager.card')),
            ],
        ),
    ]
