# Generated by Django 5.1.3 on 2025-10-05 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardManager', '0013_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='card',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='cardManager.card'),
        ),
    ]
