# Generated by Django 5.1.3 on 2025-10-21 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardManager', '0014_alter_usage_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='design',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cardManager.design'),
        ),
        migrations.AlterField(
            model_name='usage',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='cardManager.card'),
        ),
    ]
