# Generated by Django 4.2.25 on 2025-11-05 23:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cardManager', '0014_alter_usage_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='cardManager.card'),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('custom_design', models.ImageField(blank=True, upload_to='userPhotos/customDesigns/')),
                ('custom_design_rear', models.ImageField(blank=True, upload_to='userPhotos/customDesigns/')),
                ('card_qty', models.IntegerField(default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='cardManager.owner')),
                ('preset_design', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='cardManager.design')),
            ],
        ),
    ]
