# Generated by Django 4.2.25 on 2025-11-06 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardManager', '0015_alter_usage_card_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='preset_design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='cardManager.design'),
        ),
    ]
