# Generated by Django 4.2.25 on 2025-11-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardManager', '0016_alter_request_preset_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('printed', 'Printed'), ('Adhered', 'Adhered'), ('complete', 'Complete')], default='Pending', max_length=10),
        ),
    ]
