# Generated by Django 4.2.27 on 2025-12-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardManager', '0021_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='token',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
