# Generated by Django 4.2.27 on 2025-12-16 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardManager', '0022_alter_card_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='design',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cardManager.design'),
        ),
    ]
