# Generated by Django 4.2.27 on 2026-04-07 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardManager', '0023_alter_card_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='alias',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cardManager.design'),
        ),
    ]
