# Generated by Django 4.2.27 on 2026-05-14 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardManager', '0024_design_is_public_alter_card_alias_alter_card_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='rear_design',
            field=models.ImageField(blank=True, upload_to='cardDesigns/'),
        ),
    ]
